install:
  skip
script:
  - ./sde_to_json.sh
before_deploy:
  - if [[ -e gittag ]]; then
    source ./gittag;
    git tag ${gittag};
    fi
deploy:
  provider: releases
  token: $GH_TOKEN
  overwrite: true
  file: 
    - mapRegions.json
    - staStations.json
  cleanup: false
  on:
    tags: false
