env:
  global:
    - secure: "okzCgCH5MF+jspHpPvGKkS3+aP5wlGgKnNaAybfGQpWyhdbI6pTvEbe1I4kFW9dX+Mc2T12JWFwbhKx5n5DqYcUk9SquxBySe9DaZveEGeD6QwRa8BR+FiSOt3jxlpqtYYT6FLUSGJSu+PMuCQXdZ9v1y+5yTX3Zi5GZj1xcr8L2BXxv9a/BU7ZHxW4Rh2MNZpWZxIzQopwbwQh9yCzvrLHzsZfMpM4aNfSax7xYc3p5PpV26SR95Q4fUIVIodvFPS8mWJeHI6BAdLpuguo9hePO/WKN9E4xRLBn4IjZtNt9+w2DZYC5z6oLO7rAj2DbEqCZ0vQn+GzPmYNAjw/AjT9QH4AHToK6xxFxxOdehNgVT4Os+SyOVx9YQ7WhgRZ8pE1z0V7NN+eyBmtf/8xv+GZ4tcqJctc8nja8NIwcS5G037/H7Gy1KfayEAGglc0iWxAupt3rcYrZeUYGBvwMOAuEL/B4RHF7hFjS2fjXu4LQmRD14K9p/pY4/cuhUTlxBmBy6Uf3dGUzOS8++R3bLfkc5WSQ/WEvEV5y0pbYzwJCkQCfFFgeDhXxP+SMy9IQxLdDC/+9tal1Wo2uoRvU0QuZpgY1dT5b5cwd2qEAgT68u0QvtsBedv6y0Gaeb8AD7VDalT+ixB/mot/oi/nXqcolBVzPOewH2X1+w2/VHqU="
install:
  skip
before_script:
  - |

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       # Decrypt the file containing the private key

       openssl aes-256-cbc \
         -K $encrypted_46d5c4daa580_key \
         -iv $encrypted_46d5c4daa580_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       # Enable SSH authentication

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

script:
  - ./sde_to_json.sh
